# Generated by Django 3.2.12 on 2022-02-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Categoria')),
                ('regra_contabilizacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Regra de Contabilização')),
                ('conta_contabil', models.CharField(blank=True, max_length=18, null=True, verbose_name='Conta Contábil')),
                ('dre', models.CharField(blank=True, max_length=155, null=True, verbose_name='DRE')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('razaosocial', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('codigo_erp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código ERP')),
                ('data_criacao', models.DateField(blank=True, null=True, verbose_name='Data da Criação')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='planocontas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Informe o código do plano de contas', max_length=14, verbose_name='Código')),
                ('descricao', models.CharField(help_text='Informe a descrição do plano de contas', max_length=155, verbose_name='Descrição')),
                ('reduzido', models.CharField(blank=True, max_length=3, null=True, verbose_name='Reduzido')),
                ('analitica', models.BooleanField(default=False, verbose_name='Analítica')),
                ('patrimonial', models.BooleanField(default=False, verbose_name='Patrimonial')),
                ('natureza', models.CharField(choices=[('C', 'Credora'), ('D', 'Devedora')], max_length=1, verbose_name='Natureza')),
                ('seq', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seq')),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_plano_contas', to='config.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Plano de Contas',
            },
        ),
    ]
