# Generated by Django 3.2.12 on 2022-02-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_categoria_conta_contabil'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='empresas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_empresa', to='config.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
