# Generated by Django 3.2.12 on 2022-02-18 18:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_categoria_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Jurídica', 'Jurídica'), ('Física', 'Física')], max_length=50, verbose_name='Tipo de  pessoa')),
                ('razaosocial', models.CharField(max_length=250, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=250, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Principal')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefone')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Abertura da empresa')),
                ('simples', models.BooleanField(default=False, verbose_name='Optante pelo simples?')),
                ('indicador_ie', models.CharField(blank=True, choices=[('Não Contribuinte', 'Não Contribuinte'), ('Contribuinte', 'Contribuinte'), ('Contribuinte isento', 'Contribuinte isento')], max_length=100, null=True, verbose_name='Indicador de Inscrição Estadual')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal')),
                ('cep', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('municipio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('pessoa_contato', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pessoa de Contato')),
                ('pessoa_contato_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('pessoa_contato_telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefone')),
                ('pessoa_contato_cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo')),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
