# Generated by Django 3.2.12 on 2022-02-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Municípo'),
        ),
        migrations.CreateModel(
            name='conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50, verbose_name='Banco')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('agencia', models.CharField(max_length=50, verbose_name='Descrição')),
                ('conta', models.CharField(max_length=50, verbose_name='Conta')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_empresa', to='config.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
