# Generated by Django 3.2.12 on 2022-02-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20220218_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='agencia',
            field=models.CharField(max_length=50, verbose_name='Agência'),
        ),
        migrations.CreateModel(
            name='centrocustos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custos_empresa', to='config.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custos',
            },
        ),
    ]
