# Generated by Django 3.2.12 on 2022-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20220218_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocustos',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
