# Generated by Django 3.2.12 on 2022-02-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0007_centrocustos_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='contasapagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_competencia', models.DateField(verbose_name='Data competência')),
                ('data_vencimento', models.DateField(verbose_name='Data vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('documentos', models.FileField(blank=True, help_text='Anexe o documento, como Nota Fiscal, Recibo', null=True, upload_to='uploads/documents/%Y/%m/%d/', verbose_name='Documentos')),
                ('boletos', models.FileField(blank=True, help_text='Anexe o boleto para pagamento', null=True, upload_to='uploads/documents/%Y/%m/%d/', verbose_name='Boletos')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data pagamento')),
                ('descontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descontos')),
                ('juros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Juros')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_a_pagar_categoria', to='config.categoria', verbose_name='Categoria')),
                ('centrocustos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_a_pagar_empresa', to='config.centrocustos', verbose_name='Centro de Custos')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_a_pagar_conta', to='config.conta', verbose_name='Conta')),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_a_pagar_empresa', to='config.empresa', verbose_name='Empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_a_pagar_fornecedor', to='config.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Contas a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
    ]
